### ISSUE TITLE
Failed to find X11-XCB libraries, try `sudo apt-get install xcb libx11-dev   libxcb-randr0-dev`

### ISSUE THREAD

**Issue by zhangfq-chemistry** [MethanePowered/MethaneKit#146]
Ubuntu 24 system: sudo apt-get install xcb libx11-dev libxcb-randr0-dev:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxcb-randr0-dev is already the newest version (1.14-3ubuntu3).
xcb is already the newest version (2.4-8).
libx11-dev is already the newest version (2:1.7.5-1ubuntu0.3).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

**Comment by egorodet** [comment]
@zhangfq-chemistry I don't see the problem from your description. APT command says that the libraries are already installed on your system. Command did not fail to find any libraries. Please provide more details about your issue.

**Comment by zhangfq-chemistry** [comment]
I have installed xcb but failed to cmake with error:
CMake Error at CMake/MethaneGlobalOptions.cmake:114 (message):
  Failed to find X11-XCB libraries, try `sudo apt-get install xcb libx11-dev
  libxcb-randr0-dev`
Call Stack (most recent call first):
  CMakeLists.txt:151 (include)

**Comment by egorodet** [comment]
> I have installed xcb but failed to cmake with error: CMake Error at CMake/MethaneGlobalOptions.cmake:114 (message): Failed to find X11-XCB libraries, try `sudo apt-get install xcb libx11-dev libxcb-randr0-dev` Call Stack (most recent call first): CMakeLists.txt:151 (include)

CMake instruction contains incomplete list of X11 libraries. See full list of required libraries in [Build/README.md](../tree/master/Build/README.md):
```shell
sudo apt-get update && sudo apt-get install build-essential git cmake lcov xcb libx11-dev libx11-xcb-dev libxcb-sync-dev libxcb-randr0-dev
```

Hope this would help.

**Comment by zhangfq-chemistry** [comment]
Thanks! Ok now!
